### ISSUE TITLE
Tap gesture recognizer being called during swipe

### ISSUE THREAD

**Issue by mr746866** [Drakon-Cocos/cocos2dx-gesture-recognizers#1]
I added both `TapGestureRecognizer` and `SwipeGestureRecognizer` to my Scene like below.

```
TapGestureRecognizer * tapGestureRecognizer = TapGestureRecognizer::create(1, 1, 0.5);
tapGestureRecognizer->onTap = CC_CALLBACK_1(GamePlayLayer::onTap, this);
this->addChild(tapGestureRecognizer);

SwipeGestureRecognizer * swipeGestureRecognizer = SwipeGestureRecognizer::create();
swipeGestureRecognizer->onSwipe = CC_CALLBACK_1(GamePlayLayer::onSwipe, this);
this->addChild(swipeGestureRecognizer);
```

When I swipe on Screen the onTap method is also invoked (multiple times). 

What can I do to make it such that onTap is not called at all when user swipes?

**Comment by alfogrillo** [comment]
Can I see your `onTap` code?

**Comment by mr746866** [comment]
I already removed the code (using another library) but from memory I think it was something like the following.

```
void GamePlayLayer::onTap(TapGestureRecognizer * recognizer)
{
    log("Tap");
}
```

**Comment by alfogrillo** [comment]
The tap handler should be like this:

```
void ScrollViewCustom::onTap(TapGestureRecognizer* recognizer) 
{
    auto status = recognizer->getStatus();
    if (status == GestureStatus::RECOGNIZED)
    {
        log("Tap");
    }
}
```

The `if` is needed because onTap is called when other events occur (e.g. tap recognition begin).
Therefore you must use the status to understand in which case you are!

See here for further details:
https://developer.apple.com/library/ios/documentation/EventHandling/Conceptual/EventHandlingiPhoneOS/GestureRecognizer_basics/GestureRecognizer_basics.html

**Comment by mr746866** [comment]
Is onTap called at touch began? or at touch ended?

**Comment by alfogrillo** [comment]
`onTap` will be called when some "gesture event" occurs.

In the case of the tap when:
- Gesture recognition began
- Gesture fail
- Gesture is recognized

This is the reason why you got `onTap` called multiple times!
You can distinguish the case using the `getStatus()` function.

**Comment by mr746866** [comment]
Thank you for clearing. 

Your library is much easier to use than other similar gesture recognition libraries. But I would suggest that you make changes so that onTap is called only once when 
1. touch ends quickly after touch begin
2. touch end and touch begin positions are close

Alternatively you can add a comment at the header file stating that you need to check if the gesture is recognized or not.
