### ISSUE TITLE
Seems to need iso646.h included

### ISSUE THREAD

**Issue by tankorsmash** [Drakon-Cocos/cocos2dx-gesture-recognizers#2]
I'm on Visual Studio 2013, I've had to `#include <iso646>` and alias `using uint = unsigned int` in a few places. 

If I can get it all working, I'll try to make a merge request.

**Comment by tankorsmash** [comment]
For anyone else, _some_ minor changes are [here](https://github.com/tankorsmash/BuildUpTheBase/commit/8ceacc292d756ca958bc8fdbfe1420bd4a6f3f2e), for using the iso include, but the import splitting up, so it's using cocos2d specific headers instead of the base one is [here](https://github.com/tankorsmash/BuildUpTheBase/commit/88851e9f319d8624b0522703fca3720817d0fe50). Haven't actually tried to run it yet, but it compiles.

**Comment by tankorsmash** [comment]
Oh man, this works so well! I'll close this since my changes don't use the USING_CC_NS style and the paths assume cocos' directories are in the include path. 

Thanks for this, sincerely!

**Comment by alfogrillo** [comment]
Hi @tankorsmash!
I'm glad you enjoy the library! 🙂
If I understood well, there is an issue with the `uint` type under Windows.
Let me know the changes you did, I'll try to fix the issue ASAP.
However I haven't access to a Windows computer in this moment, I'll need your help for the build check.
